---
kind: pipeline
type: docker
name: arm64
platform:
  os: linux
  arch: arm64
steps:
  - name: test
    image: debian:latest
    commands:
      - echo "Hello World. This is .drone.yml"
      - uname -m
      - cat /etc/hosts
      - pwd
      - env

