version: "2"

networks:
  base:

services:
  owncloud:
    image: ${TESTING_IMAGE}
    volumes:
      - ${TESTING_PATH}:/var/www/owncloud
    ports:
      - 80
    links:
      - db:db
      - cache:cache
    networks:
      - base
    environment:
      - OWNCLOUD_DOMAIN=owncloud
      - OWNCLOUD_DB_TYPE=${TESTING_DATABASE}
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=p455w0rd
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin
      - OWNCLOUD_MEMCACHED_ENABLED=true
      - OWNCLOUD_MEMCACHED_HOST=cache

  cache:
    image: memcached:alpine
    expose:
      - 11211
    networks:
      - base
