version: "2"

networks:
  general:
    internal: true

services:
  owncloud:
    image: owncloud/base:latest
    volumes:
      - ${TESTING_PATH}:/var/www/owncloud
    ports:
      - 80
    links:
      - db:db
    networks:
      - general
    environment:
      - OWNCLOUD_DOMAIN=owncloud
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=root
      - OWNCLOUD_DB_PASSWORD=p455w0rd
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin

  db:
    image: webhippie/mariadb:latest
    expose:
      - 3306
    networks:
      - general
    environment:
      - MARIADB_ROOT_PASSWORD=p455w0rd
      - MARIADB_DATABASE=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_INNODB_USE_NATIVE_AIO=0

  litmus:
    image: owncloud/litmus:${TESTING_LITMUS}
    entrypoint: ["/bin/sleep", "86400"]
    networks:
      - general
    environment:
      - LITMUS_URL=http://owncloud/remote.php/webdav
      - LITMUS_USERNAME=admin
      - LITMUS_PASSWORD=admin
      - LITMUS_WAIT=true
      - LITMUS_CHECK_URL=http://owncloud/status.php
    links:
      - owncloud:owncloud
