version: "2"

services:
  owncloud:
    image: owncloud/base:latest
    volumes:
      - ${TESTING_PATH}:/var/www/owncloud
    ports:
      - ${TESTING_PORT}:80
    links:
      - db:db
    environment:
      - OWNCLOUD_DOMAIN=owncloud
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=p455w0rd
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin

  db:
    image: mysql:5
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=p455w0rd
      - MYSQL_DATABASE=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=p455w0rd

  smashbox:
    image: owncloud/smashbox:${TESTING_SMASHBOX}
    entrypoint: ["/bin/sleep", "86400"]
    environment:
      - SMASHBOX_URL=owncloud
      - SMASHBOX_USERNAME=admin
      - SMASHBOX_PASSWORD=admin
      - SMASHBOX_WAIT=true
      - SMASHBOX_TEST_NAME=${TESTING_TESTS}
      - SMASHBOX_CHECK_URL=owncloud/status.php
    links:
      - owncloud:owncloud
