version: "2"

networks:
  general:
    internal: true

services:
  owncloud:
    image: owncloud/base:latest
    volumes:
      - ${TESTING_PATH}:/var/www/owncloud
    ports:
      - 80
    links:
      - db:db
    networks:
      - general
    environment:
      - OWNCLOUD_DOMAIN=owncloud
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=root
      - OWNCLOUD_DB_PASSWORD=p455w0rd
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin

  db:
    image: webhippie/mariadb:latest
    expose:
      - 3306
    networks:
      - general
    environment:
      - MARIADB_ROOT_PASSWORD=p455w0rd
      - MARIADB_DATABASE=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_INNODB_USE_NATIVE_AIO=0

  smashbox:
    image: owncloud/smashbox:${TESTING_SMASHBOX}
    entrypoint: ["/bin/sleep", "86400"]
    networks:
      - general
    environment:
      - SMASHBOX_URL=owncloud
      - SMASHBOX_USERNAME=admin
      - SMASHBOX_PASSWORD=admin
      - SMASHBOX_WAIT=true
      - SMASHBOX_TEST_NAME=${TESTING_TESTS}
      - SMASHBOX_CHECK_URL=owncloud/status.php
    links:
      - owncloud:owncloud
